### ISSUE TITLE
dpd.js Failed to load resource:

### ISSUE THREAD

**Issue by moorthi07** [deployd/dpd-dashboard#2]
2 dpd.js Failed to load resource: the server responded with a status of 404 (Not Found)
sidebar.js:3 Uncaught ReferenceError: _dpd is not defined
    at sidebar.js:3
    at sidebar.js:6

**Comment by moorthi07** [comment]
I tested with  deployd 0.8.9

Should it be tested with 1.0.0 beta?

**Comment by NicolasRitouet** [comment]
Indeed, the dpd-dashboard requires the lib-client to work.
ideally, I would remove this dependency, but in the meanwhile, we should add this in the readme.
Can you send a PR to update the readme of `dpd-dashboard` to include that `dpd-clientlib` is required?

**Comment by moorthi07** [comment]
npm install dpd-dashboard  - also installs dpd-clientlib , but , client dpd.js call is not handled.

installing dpd-clientlib  again , dashboard works !.

**Comment by moorthi07** [comment]
Issue is with config-loader.  The package should be an entry in dependencies in package.json.

{
  "engines": {
    "node": ">= 0.10.0"
  },
  "dependencies": {
    "deployd": "^1.0.0-alpha",
    "dpd-dashboard": "0.0.1" 
  }
}

I just manually added "dpd-clientlib": "^0.8.9" to package.json
This will work - without npm install dpd-clientlib --save : after installing dpd-dashboard.
{
  "engines": {
    "node": ">= 0.10.0"
  },
  "dependencies": {
    "deployd": "^1.0.0-alpha",
    "dpd-dashboard": "0.0.1",
    "dpd-clientlib": "^0.8.9"
  }
}

Solutions could be, 
1. remove  "dpd-clientlib": "^0.8.9" from dpd-dashboard package.json dependencies. And change documentation to : npm install dpd-dashboard dpd-clientlib --save 
(Unfortunately  '--save' is a must here :) )

2. Fix it in  configloader - not recommended.
3. new code for clientlib loader in dpd-dashboard?!

**Comment by NicolasRitouet** [comment]
I would go with the first solution as a quick fix and work on removing this dependencies later

**Comment by andreialecu** [comment]
Closing this. `dpd-clientlib` should be installed explicitly in the main project so that users can specify whether they need it as a dev dependency or a normal dependency.
