### ISSUE TITLE
npm install dpd-dashboard needs a package.json.

### ISSUE THREAD

**Issue by moorthi07** [deployd/dpd-dashboard#7]
Deployd doesn't create a package.json during dpd install.
But 
npm install dpd-dashboard needs a package.json.

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\\Downloads\dpd1.0test\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\\Downloads\dpd1.0test\node_modules\dpd-old-dashboard\package.json'
npm WARN dpd1.0test No description
npm WARN dpd1.0test No repository field.
npm WARN dpd1.0test No README data
npm WARN dpd1.0test No license field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "dpd-dashboard"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\\Downloads\dpd1.0test\node_modules\dpd-dashboard
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall access

npm ERR! enoent ENOENT: no such file or directory, access 'C:\Users\\Downloads\dpd1.0test\node_modules\dpd-dashboard'
npm ERR! enoent ENOENT: no such file or directory, access 'C:\Users\\Downloads\dpd1.0test\node_modules\dpd-dashboard'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\\Downloads\dpd1.0test\npm-debug.log

**Comment by andreialecu** [comment]
Probably `deployd-cli` should create a package.json.

In the mean time, you can run `npm init` in the folder.

**Comment by andreialecu** [comment]
Reopen this issue in the `deployd-cli` repository.

**Comment by moorthi07** [comment]
Hi, @andreialecu  The question is why is this module needs a package.json ? The previous version didn't needed it. So I was able to run dashboard and  create resources . This new version is breaking and making the install sequence  complex.

**Comment by moorthi07** [comment]
As I said, if I don't use 'dpd create' (which is working fine . creates a package.json'.). But dpd-dashboard - previous version didn't depend on 'package.json'. The new version also shouldn't.
