### ISSUE TITLE
renaming '/dpd-dashboard' folder should not work

### ISSUE THREAD

**Issue by moorthi07** [deployd/dpd-dashboard#8]
Not sure it is a node/npm problem or dpd type-loader problem.  OR  its  the 'require' problem . I haven't tried any other node packages for this issue.

Renaming /node-modules/dpd-dashboard - still works. 
I tried with both prefix and suffix. Both working?! (1dpd-dashboard or dpd-dashboard-old)

But if you change the inner folder '/node-modules/dpd-dashboard /dashbord' it won't work.

**Comment by andreialecu** [comment]
I'm not sure what you're saying here. Why is this a problem?

**Comment by moorthi07** [comment]
I'm working and testing. But this is an issue. Its happening. :)

**Comment by andreialecu** [comment]
I don't understand what the issue here is. Renaming the inner `/dashboard` folder is obviously not a good idea as it will break things. Renaming the folder under `node_modules` is not necessarily a problem and things will still work, that's how node works.
